// PDF
const BLOG_SCRIPT_FONT = 'BlogScript';
const GOTHAM_BOLD_FONT = 'GothamBold';
const GOTHAM_BOOK_FONT = 'GothamBook';
const GOTHAM_BOOK_ITALIC_FONT = 'GothamBookItalic';

const LINE_HEIGHT_NORMAL_SENTENCE = 1.273;
const A4_FULL_WIDTH_POINT = 595; // 595.28 - 595
const A4_FULL_HEIGHT_POINT = 842; // 841.89 - 842

export const PAGE_STYLE = {
  fontFamily: 'Gotham',
  margin: 0,
  padding: 0
};

export const PAGE_STYLE_ADULTS = {
  fontFamily: 'Bariol',
  margin: 0,
  padding: 0
};

export const PORTRAIT: any = [A4_FULL_WIDTH_POINT, A4_FULL_HEIGHT_POINT];
export const LANDSCAPE: any = [A4_FULL_HEIGHT_POINT, A4_FULL_WIDTH_POINT];

const PDF_PAGE_INDEX = {
  INTRODUCTION: 1,
  DISCLAIMER: 2,
  DEAR: 3,
  TABLE_CONTENT: 4,
  MICROBIOME: 5,
  COMPOSITION: 6,
  COMPARISON: 7,
  TIP: 8,
  SUPPORT: 9,
  WHAT_TO_EAT: 10,
  PLATE: 11,
  DIET: 12,
  THANK_YOU: 13,
  NATURE: 14,
  BIFI_LOVE: 15,
  BABY_SUPPORT: 16,
  FACT_ABOUT: 17,
  FACT_HELLO: 18,
  FACT_DIAGRAM: 19,
  FACT_DESCRIPTION: 20,
  SUMMARY_MICROBES: 21,
  MICRO_INDICATE: 22,
  MICRO_INDICATE_OVER: 23,
  MICROMETER: 24,
  C_SECTION: 25,
  INFORMATIONHCP: 26,
  C_SECTION_TWO: 27,
  IMPORTANT_HCP: 28,
  RESULTS_FOOD_FOR_FFQ: 28,
  GUIDELINE_RECOMMENDATION_FOR_FFQ: 29,
  MILESTONES_PAGE_FOR_FFQ: 30,
  MILESTONES_PAGE2_FOR_FFQ: 31,
  INSIGHTS_FROM_YOUR_FOOD: 32,
  FOOD_GROUPS_INSUFFICIENT: 33,
  DISCLAIMER_FOR_FFQ: 34,
  QUICK_TIP: 35
};

export {
  BLOG_SCRIPT_FONT,
  GOTHAM_BOLD_FONT,
  GOTHAM_BOOK_FONT,
  GOTHAM_BOOK_ITALIC_FONT,
  LINE_HEIGHT_NORMAL_SENTENCE,
  A4_FULL_WIDTH_POINT,
  A4_FULL_HEIGHT_POINT,
  PDF_PAGE_INDEX
};
